"""Deterministic crisis classifier for the Wellness Agent.

This is SAFETY-CRITICAL. Detection of self-harm, suicidal ideation, or abuse
triggers escalation protocol — NOT generative therapy responses.

WARNING: Human clinical review is required before any real deployment.
"""

import logging
import re
from typing import List, Tuple

logger = logging.getLogger(__name__)

# Crisis signal keywords (deterministic, not ML-based, to minimize false negatives)
CRISIS_KEYWORDS = {
    "high": [
        "kill myself", "end my life", "want to die", "suicide", "suicidal",
        "not want to live", "better off dead", "harm myself", "self-harm",
        "hurt myself", "taking my life", "end it all", "no reason to live",
    ],
    "medium": [
        "hopeless", "worthless", "no way out", "cant take it", "can't take it",
        "give up", "giving up", "dont want to be here", "don't want to be here",
        "nobody cares", "alone", "no one understands",
    ],
    "low": [
        "stressed", "anxious", "worried", "scared", "nervous", "overwhelmed",
        "pressure", "tired", "burnout", "exhausted",
    ],
}

# Verified India helpline numbers — configurable constant, NEVER generated by LLM
HELPLINES = [
    {"name": "iCall Mental Health Helpline", "number": "9152987821", "hours": "Mon-Sat 10am-8pm"},
    {"name": "Vandrevala Foundation", "number": "9999666555", "hours": "24x7"},
    {"name": "KIRAN Mental Health Helpline", "number": "18005990019", "hours": "24x7"},
    {"name": "Childline India", "number": "1098", "hours": "24x7"},
    {"name": "Jeevan Aastha Helpline", "number": "18002337330", "hours": "24x7"},
]


def classify_crisis_risk(text: str) -> Tuple[str, List[str]]:
    """Deterministically classify crisis risk level from text.

    Args:
        text: The student's input text.

    Returns:
        Tuple of (risk_level, matched_keywords).
        risk_level: 'high', 'medium', 'low', or 'none'.
    """
    text_lower = text.lower()
    matched = []

    for level, keywords in CRISIS_KEYWORDS.items():
        for keyword in keywords:
            if keyword in text_lower:
                matched.append(keyword)
                if level == "high":
                    return ("high", matched)

    if matched:
        return ("medium", matched) if matched else ("none", [])

    return ("none", [])


def get_crisis_helplines() -> List[dict]:
    """Return the verified helpline list (never generated by LLM)."""
    return HELPLINES


def build_crisis_response(risk_level: str) -> str:
    """Build a pre-approved safe response based on risk level.

    Never lets the LLM generate crisis responses — uses pre-approved templates.
    """
    helplines_text = "\n".join(
        [f"  - {h['name']}: {h['number']} ({h['hours']})" for h in HELPLINES]
    )

    if risk_level == "high":
        return (
            "I'm really concerned about what you're sharing. Your well-being is the most important thing right now. "
            "Please reach out to a mental health professional immediately.\n\n"
            "Here are helplines available 24x7:\n"
            f"{helplines_text}\n\n"
            "You can also reach out to a trusted adult, family member, or teacher. "
            "You are not alone — please get the support you deserve."
        )
    elif risk_level == "medium":
        return (
            "I hear you, and I want you to know that what you're feeling matters. "
            "Please consider speaking to someone you trust about how you're feeling.\n\n"
            "Here are some helplines that can help:\n"
            f"{helplines_text}\n\n"
            "Remember, it's okay to ask for help."
        )
    else:
        return ""
